pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile'
            dir 'sample_job'
            args '-u root'
        }
    }
    options {
        buildDiscarder(
            logRotator(
                daysToKeepStr: '1',
                numToKeepStr: '1',
                artifactDaysToKeepStr: '1',
                artifactNumToKeepStr: '1'
            )
        )
    }
    stages {
        stage('Build') {
            steps {
                sh '/app/job.sh'
            }
            post {
                success {
                    arvhiveArtifacts "*.txt"
                }
            }
        }
    }
}
